# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  packer_config = debug
  raylib_config = debug
  taco_config = debug
  sandbox_config = debug
  taco_shell_config = debug

else ifeq ($(config),release)
  packer_config = release
  raylib_config = release
  taco_config = release
  sandbox_config = release
  taco_shell_config = release

else ifeq ($(config),dist)
  packer_config = dist
  raylib_config = dist
  taco_config = dist
  sandbox_config = dist
  taco_shell_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := packer raylib taco sandbox taco-shell

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

packer:
ifneq (,$(packer_config))
	@echo "==== Building packer ($(packer_config)) ===="
	@${MAKE} --no-print-directory -C packer -f Makefile config=$(packer_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C taco/lib/raylib -f Makefile config=$(raylib_config)
endif

taco: packer raylib
ifneq (,$(taco_config))
	@echo "==== Building taco ($(taco_config)) ===="
	@${MAKE} --no-print-directory -C taco -f Makefile config=$(taco_config)
endif

sandbox: taco
ifneq (,$(sandbox_config))
	@echo "==== Building sandbox ($(sandbox_config)) ===="
	@${MAKE} --no-print-directory -C sandbox -f Makefile config=$(sandbox_config)
endif

taco-shell: taco
ifneq (,$(taco_shell_config))
	@echo "==== Building taco-shell ($(taco_shell_config)) ===="
	@${MAKE} --no-print-directory -C taco-shell -f Makefile config=$(taco_shell_config)
endif

clean:
	@${MAKE} --no-print-directory -C packer -f Makefile clean
	@${MAKE} --no-print-directory -C taco/lib/raylib -f Makefile clean
	@${MAKE} --no-print-directory -C taco -f Makefile clean
	@${MAKE} --no-print-directory -C sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C taco-shell -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   packer"
	@echo "   raylib"
	@echo "   taco"
	@echo "   sandbox"
	@echo "   taco-shell"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"